<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Ворота, заборы Иркутск");
$APPLICATION->SetTitle("Каталог");
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"catalog", 
	array(
		"IBLOCK_TYPE" => "aspro_stroy_catalog",
		"IBLOCK_ID" => "20",
		"NEWS_COUNT" => "15",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "N",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/catalog/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "DETAIL_PICTURE",
			4 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "TYPE_BUILDINGS",
			1 => "FORM_QUESTION",
			2 => "FORM_ORDER",
			3 => "SHOW_ON_INDEX_PAGE",
			4 => "ARTICLE",
			5 => "TYPE",
			6 => "COLOR",
			7 => "SIZE_ZHILAYA",
			8 => "SIZE_KUXNI",
			9 => "LINK_PROJECTS",
			10 => "GARAGE",
			11 => "SLEEP_ROOM",
			12 => "APPOINTMENT",
			13 => "STIKERS",
			14 => "TIZERS",
			15 => "SIZE",
			16 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"SORT_PROP" => array(
		),
		"SORT_PROP_DEFAULT" => "name",
		"SORT_DIRECTION" => "asc",
		"DISPLAY_NAME" => "N",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "FORM_QUESTION",
			1 => "FORM_ORDER",
			2 => "PRICE",
			3 => "PRICEOLD",
			4 => "ARTICLE",
			5 => "TYPE",
			6 => "PLOSHAD",
			7 => "SIZEV",
			8 => "SKOROST",
			9 => "KRYTMOMENT",
			10 => "COLOR",
			11 => "ELECTRODV",
			12 => "DVV",
			13 => "SKOROST_OT",
			14 => "PREDOHRAN",
			15 => "PEREDACHA",
			16 => "REZHIM",
			17 => "VETR",
			18 => "USIL",
			19 => "GRGOR",
			20 => "SIZE_ZHILAYA",
			21 => "GRVOS",
			22 => "VESP",
			23 => "SIZE_KUXNI",
			24 => "DIAP",
			25 => "MOMENT",
			26 => "IP",
			27 => "IN",
			28 => "LINK_PROJECTS",
			29 => "TEPLOP",
			30 => "ZVUKOIZ",
			31 => "VODONEP",
			32 => "PREDEL_OG",
			33 => "SOPRTEP",
			34 => "SOPRVETR",
			35 => "KOLCICL",
			36 => "OBVOZD",
			37 => "GARAGE",
			38 => "SLEEP_ROOM",
			39 => "APPOINTMENT",
			40 => "STIKERS",
			41 => "SIZE",
			42 => "STATUS",
			43 => "BRAND",
			44 => "DOCUMENTS",
			45 => "PLANIROVKA",
			46 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"VIEW_TYPE" => "table",
		"SHOW_IMAGE" => "Y",
		"SHOW_NAME" => "Y",
		"SHOW_DETAIL" => "Y",
		"IMAGE_POSITION" => "top",
		"COUNT_IN_LINE" => "3",
		"AJAX_OPTION_ADDITIONAL" => "",
		"USE_REVIEW" => "N",
		"ADD_ELEMENT_CHAIN" => "N",
		"SHOW_DETAIL_LINK" => "Y",
		"USE_SHARE" => "Y",
		"S_ASK_QUESTION" => "Получить консультацию",
		"S_ORDER_PRODUCT" => "Рассчитать",
		"T_GALLERY" => "",
		"T_DOCS" => "",
		"T_PROJECTS" => "Виды",
		"T_CHARACTERISTICS" => "",
		"FILTER_URL_TEMPLATE" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		"COMPONENT_TEMPLATE" => "catalog",
		"SET_LAST_MODIFIED" => "N",
		"T_VIDEO" => "",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "FILTER_PRICE",
			1 => "SIZE",
			2 => "COLOR",
			3 => "SIZE_ZHILAYA",
			4 => "SIZE_KUXNI",
			5 => "GARAGE",
			6 => "SLEEP_ROOM",
			7 => "APPOINTMENT",
			8 => "",
		),
		"PROP_1" => "TYPE_BUILDINGS",
		"PROP_2" => "TYPE_BUILDINGS",
		"PROP_3" => "TYPE_BUILDINGS",
		"S_DETAIL_PRODUCT" => "Подробнее",
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_BRAND_PROP_CODE" => array(
			0 => "TIZERS",
			1 => "",
		),
		"T_PLANS" => "Схемы",
		"SHOW_SLIDE_PROP" => array(
		),
		"STRICT_SECTION_CHECK" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"SHARE_HIDE" => "N",
		"SHARE_TEMPLATE" => "",
		"SHARE_HANDLERS" => array(
			0 => "mailru",
			1 => "vk",
			2 => "delicious",
			3 => "lj",
			4 => "twitter",
			5 => "facebook",
		),
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_SHORTEN_URL_KEY" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"detail" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		)
	),
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>