<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Забор из евроштакетника с установкой в Иркутске");
$APPLICATION->SetPageProperty("description", "Забор из евроштакетника с установкой в Иркутске. Бережно доставим. Грамотно установим. Достойное качество на долгие годы. Гарантия выгодной цены.");
$APPLICATION->SetTitle("Каталог");
/*$templateName = 'catalog';
if ($USER->IsAdmin()) $templateName = 'newcatalog';*/
$templateName = 'newcatalog';
?><?$APPLICATION->IncludeComponent(
	"bitrix:news",
	$templateName,
	Array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"CHECK_DATES" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"COUNT_IN_LINE" => "3",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_BRAND_PROP_CODE" => array("TIZERS",""),
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array("NAME","PREVIEW_TEXT","DETAIL_TEXT","DETAIL_PICTURE",""),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array("FORM_QUESTION","FORM_ORDER","PRICE","PRICEOLD","ARTICLE","TYPE","PLOSHAD","SIZEV","SKOROST","KRYTMOMENT","COLOR","ELECTRODV","DVV","SKOROST_OT","PREDOHRAN","PEREDACHA","REZHIM","VETR","USIL","GRGOR","SIZE_ZHILAYA","GRVOS","VESP","SIZE_KUXNI","DIAP","MOMENT","IP","IN","LINK_PROJECTS","TEPLOP","ZVUKOIZ","VODONEP","PREDEL_OG","SOPRTEP","SOPRVETR","KOLCICL","OBVOZD","GARAGE","SLEEP_ROOM","APPOINTMENT","STIKERS","TIZERS","SIZE","STATUS","BRAND","DOCUMENTS","PLANIROVKA",""),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_AS_RATING" => "rating",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "N",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILTER_FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_NAME" => "",
		"FILTER_PROPERTY_CODE" => array(0=>"FILTER_PRICE",1=>"SIZE",2=>"COLOR",3=>"SIZE_ZHILAYA",4=>"SIZE_KUXNI",5=>"GARAGE",6=>"SLEEP_ROOM",7=>"APPOINTMENT",8=>"",),
		"FILTER_URL_TEMPLATE" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		"FORUM_ID" => "1",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "20",
		"IBLOCK_TYPE" => "aspro_stroy_catalog",
		"IMAGE_POSITION" => "left",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array("NAME","PREVIEW_TEXT","PREVIEW_PICTURE","DETAIL_PICTURE",""),
		"LIST_PROPERTY_CODE" => array("TYPE_BUILDINGS","FORM_QUESTION","FORM_ORDER","SHOW_ON_INDEX_PAGE","ARTICLE","TYPE","COLOR","SIZE_ZHILAYA","SIZE_KUXNI","LINK_PROJECTS","GARAGE","SLEEP_ROOM","APPOINTMENT","STIKERS","TIZERS","SIZE",""),
		"MAX_VOTE" => "5",
		"MESSAGES_PER_PAGE" => "10",
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "15",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROP_1" => "TYPE_BUILDINGS",
		"PROP_2" => "TYPE_BUILDINGS",
		"PROP_3" => "TYPE_BUILDINGS",
		"REVIEW_AJAX_POST" => "Y",
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => Array("detail"=>"#SECTION_CODE_PATH#/#ELEMENT_CODE#/","news"=>"","section"=>"#SECTION_CODE_PATH#/"),
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHARE_HANDLERS" => array(0=>"mailru",1=>"vk",2=>"delicious",3=>"lj",4=>"twitter",5=>"facebook",),
		"SHARE_HIDE" => "N",
		"SHARE_SHORTEN_URL_KEY" => "",
		"SHARE_SHORTEN_URL_LOGIN" => "",
		"SHARE_TEMPLATE" => "",
		"SHOW_404" => "N",
		"SHOW_DETAIL" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_IMAGE" => "Y",
		"SHOW_LINK_TO_FORUM" => "Y",
		"SHOW_NAME" => "Y",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SHOW_SLIDE_PROP" => array(),
		"SHOW_TABS" => "Y",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "NAME",
		"SORT_DIRECTION" => "asc",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"SORT_PROP" => array(),
		"SORT_PROP_DEFAULT" => "name",
		"STRICT_SECTION_CHECK" => "N",
		"S_ASK_QUESTION" => "Получить консультацию",
		"S_DETAIL_PRODUCT" => "Подробнее",
		"S_ORDER_PRODUCT" => "Рассчитать",
		"T_CHARACTERISTICS" => "",
		"T_DOCS" => "",
		"T_GALLERY" => "",
		"T_PLANS" => "Схемы",
		"T_PROJECTS" => "Каталог",
		"T_VIDEO" => "",
		"URL_TEMPLATES_READ" => "",
		"USE_CAPTCHA" => "Y",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "Y",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y",
		"VIEW_TYPE" => "list",
		"VOTE_NAMES" => array("1","2","3","4","5","")
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>